### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by arunodhayan** [sharathadavanne/seld-dcase2020#1]
the dataset .z01 or .z02 extensions also contains the same files as in .zip files 

am I correct because when I unzip the files it is asking should the files be replaced

**Comment by polarch** [comment]
Hi arunodhayan, these are split zip files and they should be combined and extracted alltogether.

You could try this from the console, on linux/osx:

**I. Create split zip archive**

To create a split zip archive (a series of files named zip, z01, z02...), run following command in Terminal:
`zip -s 100m -x "*.DS_Store" -r split-foo.zip foo/`

**II. Extract split zip archive**

To extract a split zip archive (a series of files named zip, z01, z01...), run following command in Terminal:

First, combine the split archive to a single archive:
`zip -s 0 split-foo.zip --out unsplit-foo.zip`
Extract the single archive using unzip:
`unzip unsplit-foo.zip`

**Comment by arunodhayan** [comment]
what is that foo/ folder am confused
now I have 3 files foa_dev.z01, foa_dev.z02, foa_dev.zip
should i combine them and then unzip

**Comment by sharathadavanne** [comment]
Hi @arunodhayan in the folder where you have the files - foa_dev.z01, foa_dev.z02, foa_dev.zip
first run the following command, which will combine these split zip files into one big zip file.
`zip -s 0 foa_dev.zip --out foa_dev_combined.zip`
Thereafter, unzip the combined zip file by running the following command
`unzip foa_dev_combined.zip`
Thats it.
