### ISSUE TITLE
 i find the code is wrong

### ISSUE THREAD

**Issue by yangdongchao** [sharathadavanne/seld-dcase2020#8]
I think the following code is wrong.
`  for nb_rnn_filt in rnn_size:
        # print('nb_rnn_filt ',nb_rnn_filt)
        # print('spec_cnn ',spec_cnn.shape)
        spec_rnn = Bidirectional(
            GRU(nb_rnn_filt, activation='tanh', dropout=dropout_rate, recurrent_dropout=dropout_rate,
                return_sequences=True),
            merge_mode='mul'
        )(spec_rnn)
`
I find when the code run, it will break.
the detail is:   Shape must be at least rank 3 but is rank 2 for '{{node BiasAdd}} = BiasAdd[T=DT_FLOAT, data_format="NCHW"](MatMul, unstack)' with input shapes: [?,384], [384].

**Comment by sharathadavanne** [comment]
Hi @yangdongchao this is Keras version problem. Please use the suggested versions [here](https://github.com/sharathadavanne/seld-dcase2020#prerequisites) to run it successfully.
